### ISSUE TITLE
listen: operation not permitted

### ISSUE THREAD

**Issue by plant7403** [reddec/redirect#2]
Hi, trying to run it with snap(ubuntu20.10/arm64) and get this:

UI: 127.0.0.1:10101
Bind: 0.0.0.0:10100
panic: listen tcp 127.0.0.1:10101: listen: operation not permitted

goroutine 1 [running]:
main.main()
        /build/redirect-to/parts/cli/go/src/github.com/reddec/redirect/cmd/redirect/main.go:46 +0x73c

**Comment by reddec** [comment]
Try to run with `sudo` or install with `--classic` mode. It seems like new restrictions from Ubuntu Snap store.

**Comment by plant7403** [comment]
➜  ~ sudo snap install redirect-to --classic
Warning: flag --classic ignored for strictly confined snap redirect-to

redirect-to 0+git.a86ecce from Baryshnikov Aleksandr (reddec) installed

**Comment by reddec** [comment]
Fixed in v1.1.1

Thank you for the issue. Please update your package (or just re-install). If it will not help - please re-open the issue.
